# Generated by Django 6.0.7 on 2026-09-01 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_welcome_email_sent'),
        ('account', '0002_lawyerprofile'),
    ]

    operations = [
    ]
