# Generated by Django 4.2 on 2026-08-06 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفرع')),
                ('city', models.CharField(max_length=50, verbose_name='المدينة')),
                ('address', models.TextField(verbose_name='العنوان التفصيلي')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الأتعاب')),
            ],
            options={
                'verbose_name': 'نوع خدمة',
                'verbose_name_plural': 'أنواع الخدمات',
            },
        ),
    ]
