# Generated by Django 6.0.7 on 2026-08-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الجوال')),
                ('subject', models.CharField(max_length=100, verbose_name='نوع الخدمة / الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المحامي')),
                ('cases_won', models.IntegerField(default=0, verbose_name='عدد القضايا المكتسبة')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='نبذة عن المحامي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='تبدأ الأتعاب من')),
                ('icon_class', models.CharField(default='fa-solid fa-briefcase', max_length=50, verbose_name='أيقونة FontAwesome')),
            ],
        ),
        migrations.DeleteModel(
            name='LawyerProfile',
        ),
    ]
