# Generated by Django 6.0.7 on 2026-08-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0002_contactmessage_lawyer_service_delete_lawyerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lawyer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='cases_won',
        ),
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.EmailField(default='test@email.com', max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='سنوات الخبرة'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(default='test@email.com', max_length=20, verbose_name='رقم الجوال'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lawyer',
            name='specialization',
            field=models.CharField(default='عام', max_length=150, verbose_name='التخصص القانوني'),
            preserve_default=False,
        ),
    ]
