# Generated by Django 6.0.7 on 2026-08-09 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0003_remove_lawyer_bio_remove_lawyer_cases_won_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=120, verbose_name='نوع القضية')),
                ('application_type', models.CharField(max_length=120, verbose_name='نوع التطبيق')),
                ('description', models.TextField(verbose_name='وصف القضية')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('assigned', 'تم التعيين'), ('in_progress', 'قيد التنفيذ'), ('closed', 'مغلق')], default='new', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lawyer.lawyer', verbose_name='المحامي')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
            ],
        ),
    ]
