# Generated by Django 6.0.7 on 2026-08-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0004_caserequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_replied',
            field=models.BooleanField(default=False, verbose_name='تم الرد'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reply',
            field=models.TextField(blank=True, null=True, verbose_name='الرد الإداري'),
        ),
    ]
