# Generated by Django 4.2 on 2026-08-10 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lawyer', '0005_contactmessage_is_replied_contactmessage_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرسل'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='user',
            field=models.OneToOneField(blank=True, help_text='ارتباط هذا السجل بمستخدم مسجل إذا كان المحامي يملك حسابًا', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
    ]
