# Generated by Django 4.2 on 2026-08-20 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0006_contactmessage_user_lawyer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التخصص الفرعي')),
                ('description', models.TextField(blank=True, verbose_name='وصف التخصص')),
            ],
            options={
                'verbose_name': 'تخصص فرعي',
                'verbose_name_plural': 'التخصصات الفرعية',
            },
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='specialization',
            field=models.CharField(max_length=150, verbose_name='التخصص الرئيسي'),
        ),
        migrations.CreateModel(
            name='OfficeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=50, unique=True, verbose_name='رقم البطاقة المهنية')),
                ('office_room', models.CharField(max_length=50, verbose_name='رقم القاعة / المكتب')),
                ('issued_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الإصدار')),
                ('lawyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office_card', to='lawyer.lawyer', verbose_name='المحامي')),
            ],
            options={
                'verbose_name': 'بطاقة مكتبية',
                'verbose_name_plural': 'البطاقات المكتبية',
            },
        ),
        migrations.AddField(
            model_name='lawyer',
            name='specializations',
            field=models.ManyToManyField(blank=True, related_name='lawyers', to='lawyer.specialization', verbose_name='التخصصات الفرعية (كثير إلى كثير)'),
        ),
    ]
