# Generated by Django 6.0.7 on 2026-09-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawyer', '0007_specialization_alter_lawyer_specialization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='lawyers/', verbose_name='صورة المحامي'),
        ),
    ]
